Update docker-push-hw4.yml

diff --git a/.github/workflows/docker-push-hw4.yml b/.github/workflows/docker-push-hw4.yml
--- a/.github/workflows/docker-push-hw4.yml
+++ b/.github/workflows/docker-push-hw4.yml
@@ -23,6 +23,12 @@ jobs:
         # 讀取 Dockerfile 中的 version
         file=hw4/${{ matrix.folder }}/Dockerfile
         version=$(grep -E '^(LABEL) +version *=*' "$file" | head -n1 | sed -E 's/.*[ =]+"?([0-9]+\.[0-9]+(\.[0-9]+)?)"?/\1/')
+
+        if [ -z "$version" ]; then
+          echo "::error::Failed to extract version from $file. Please add LABEL version=\"1.0\""
+          exit 1
+        fi
+        
         echo "tag=${{ matrix.folder }}-$version" >> $GITHUB_OUTPUT
 
     - name: Log in to Docker Hub
